# Demo notebook for testing all functionality

In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('.')

In [3]:
import torch
import numpy as np

In [4]:
from sklearn.preprocessing import MinMaxScaler

# Create the scaler object
scaler = MinMaxScaler(feature_range=(0, 1))

# Scale the values to the unit cube
scaled_values = scaler.fit_transform(np.array([1.60002601, -0.90581296, 1.97956597, -0.15188502, 1.58119624, 1.20904692, 1.98686438, -0.21746294]).reshape(-1, 1))

# Print the scaled values
print(scaled_values)

[[0.86626978]
 [0.        ]
 [0.99747694]
 [0.26063327]
 [0.85976032]
 [0.73110812]
 [1.        ]
 [0.23796295]]


In [5]:
d = 8
bounds = torch.stack([torch.zeros(d), torch.ones(d)])
bounds

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
y = torch.rand(8,1)
y

tensor([[0.1017],
        [0.6569],
        [0.9295],
        [0.2151],
        [0.4152],
        [0.0949],
        [0.1516],
        [0.0339]])

In [11]:
y.min()

tensor(0.0339)