# Demo notebook for testing all functionality

In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('.')

In [3]:
import torch
import numpy as np

In [4]:
from sklearn.preprocessing import MinMaxScaler

# Create the scaler object
scaler = MinMaxScaler(feature_range=(0, 1))

# Scale the values to the unit cube
scaled_values = scaler.fit_transform(np.array([1.60002601, -0.90581296, 1.97956597, -0.15188502, 1.58119624, 1.20904692, 1.98686438, -0.21746294]).reshape(-1, 1))

# Print the scaled values
print(scaled_values)

[[0.86626978]
 [0.        ]
 [0.99747694]
 [0.26063327]
 [0.85976032]
 [0.73110812]
 [1.        ]
 [0.23796295]]


In [5]:
d = 8
bounds = torch.stack([torch.zeros(d), torch.ones(d)])
bounds

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
y = torch.rand(8,1)
y1 = torch.rand(1,1)
y

tensor([[0.5113],
        [0.1437],
        [0.6998],
        [0.5285],
        [0.4383],
        [0.7294],
        [0.7744],
        [0.2539]])

In [14]:
torch.vstack([y, y1])

tensor([[0.5113],
        [0.1437],
        [0.6998],
        [0.5285],
        [0.4383],
        [0.7294],
        [0.7744],
        [0.2539],
        [0.7820]])

In [15]:
bounds = torch.tensor([[0.0] * 6, [1.0] * 6])
bounds

tensor([[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [16]:
torch.tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
from torch import inf
bounds = torch.tensor([[-inf] * 6, [inf] * 6])
bounds

tensor([[-inf, -inf, -inf, -inf, -inf, -inf],
        [inf, inf, inf, inf, inf, inf]])

In [22]:
torch.tensor([[-inf] * d, [inf] * d])

tensor([[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [inf, inf, inf, inf, inf, inf, inf, inf]])